// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rebt-home/Bloom.tsx": () => import("../components/mockups/rebt-home/Bloom.tsx"),
  "./components/mockups/rebt-home/Clarity.tsx": () => import("../components/mockups/rebt-home/Clarity.tsx"),
  "./components/mockups/rebt-home/Depth.tsx": () => import("../components/mockups/rebt-home/Depth.tsx")
};
